version: '3.9'

services:
  quotes-db-postgres:
    image: postgres:15.5
    container_name: quotes-db-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
      - quotes-data:/var/lib/postgresql/data

  curr-quote:
    build: ./
    command: ./curr-quote-app --docker
    container_name: curr-quote
    ports:
      - "8080:8080"
    depends_on:
      - quotes-db-postgres

volumes:
  quotes-data:
