// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "curr-quote/internal/model"
)

// Exchange is an autogenerated mock type for the Exchange type
type Exchange struct {
	mock.Mock
}

// GetLatestQuote provides a mock function with given fields: ctx, curr
func (_m *Exchange) GetLatestQuote(ctx context.Context, curr model.Currency) (model.Quote, error) {
	ret := _m.Called(ctx, curr)

	var r0 model.Quote
	if rf, ok := ret.Get(0).(func(context.Context, model.Currency) model.Quote); ok {
		r0 = rf(ctx, curr)
	} else {
		r0 = ret.Get(0).(model.Quote)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Currency) error); ok {
		r1 = rf(ctx, curr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewExchange interface {
	mock.TestingT
	Cleanup(func())
}

// NewExchange creates a new instance of Exchange. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExchange(t mockConstructorTestingTNewExchange) *Exchange {
	mock := &Exchange{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
