"postgres-quotes-db":
  "username": "root"
  "password": "root"
  "host": "localhost"
  "port": 5432
  "dbname": "postgres"
  "sslmode": "disable"

"http-server":
  "host": "localhost"
  "port": 8080
